# Generated by Django 4.1 on 2022-10-30 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.postcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id', 'author', 'heading', 'picture', 'content', 'created_at', 'category_id', 'avatar'], name='posts_post_id_fd72f1_idx'),
        ),
        migrations.AddIndex(
            model_name='postcategory',
            index=models.Index(fields=['id', 'name', 'description'], name='posts_postc_id_0d01cc_idx'),
        ),
    ]
