# Generated by Django 4.1.1 on 2022-09-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
