# Generated by Django 4.1.1 on 2022-09-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_order_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='completed',
        ),
    ]
