# Generated by Django 4.1.1 on 2022-09-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_complete_order_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
