# Generated by Django 4.1.1 on 2022-09-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('customer', '0006_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
    ]
