# Generated by Django 4.1 on 2022-10-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_discount_rate'),
        ('customer', '0007_order_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItems',
        ),
    ]
