# Generated by Django 4.1 on 2022-10-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_shippingdetails_options_alter_order_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedproducts',
            old_name='session_id',
            new_name='session',
        ),
    ]
