# Generated by Django 4.1 on 2022-10-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_order_session_productreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='date_written',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='review',
            field=models.TextField(),
        ),
    ]
