# Generated by Django 4.1 on 2022-10-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_productreviews_date_written_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
