# Generated by Django 4.1 on 2022-10-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_emailsubscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsubscriptions',
            name='customer',
        ),
        migrations.AlterField(
            model_name='emailsubscriptions',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
