# Generated by Django 4.1 on 2022-10-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_contactmessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessages',
            old_name='email',
            new_name='contact_email',
        ),
    ]
