# Generated by Django 4.1 on 2022-10-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_alter_product_category_and_more'),
        ('customer', '0021_rename_email_contactmessages_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='contactmessages',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessages',
            name='message',
            field=models.TextField(max_length=200, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessages',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='emailsubscriptions',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='date_written',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date written'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='rating',
            field=models.FloatField(verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='review',
            field=models.TextField(verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='city',
            field=models.CharField(max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(1, 'PayMe'), (2, 'Click')], verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='state',
            field=models.CharField(max_length=200, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='zipcode',
            field=models.CharField(max_length=200, verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=False, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Username'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['id', 'date_ordered', 'completed', 'customer_id', 'session_id'], name='customer_or_id_fc3900_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id', 'password', 'last_login', 'is_superuser', 'first_name', 'last_name', 'is_staff', 'is_active', 'date_joined', 'username', 'email', 'phone'], name='customer_us_id_30fcf7_idx'),
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
