# Generated by Django 4.1 on 2022-10-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_alter_product_category_and_more'),
        ('sessions', '0001_initial'),
        ('customer', '0022_orderitem_remove_orderitems_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessages',
            new_name='ContactMessage',
        ),
        migrations.RenameModel(
            old_name='EmailSubscriptions',
            new_name='EmailSubscription',
        ),
        migrations.RenameModel(
            old_name='LikedProducts',
            new_name='LikedProduct',
        ),
        migrations.RenameModel(
            old_name='ProductReviews',
            new_name='ProductReview',
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['id', 'quantity', 'date_added', 'order_id', 'product_id'], name='customer_or_id_86b07a_idx'),
        ),
    ]
